### ISSUE TITLE
mini-E5 STM32CubeIDE LORAWAN_End_Node wrong IOC File

### ISSUE THREAD

**Issue by wpfundstein** [Seeed-Studio/LoRaWan-E5-Node#20] opened 2024-02-27 21:15 UTC
Hi,

i downloaded the LORAWAN_End_Node Project for STM32CubeIDE

i can compile and upload the hex file to the mini-E5 and it works.

Now i want to configure some Input and Output GPIO but when i save and generate the code i get errors. the reason is incomplete configuratation in LORAWAN.

i think the ioc file is not for the mini-E5

what is wrong?

thanks, Werner

**Comment by marekpow** [comment] 2024-02-27 21:31
Try this: [link](https://github.com/Seeed-Studio/LoRaWan-E5-Node). It works for me.

**Comment by wpfundstein** [comment] 2024-02-27 21:34
> Try this: [link](https://github.com/Seeed-Studio/LoRaWan-E5-Node). It works for me.

i work with this project files and have issues with the ioc file.

thanks

PS: maybe a problem with my STM32CubeIDE Version?

STM32CubeIDE
Version: 1.14.1
Build: 20064_20240111_1413 (UTC)
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.8.1+1
Java version: 17.0.8.1

**Comment by KonRoz** [comment] 2024-03-20 17:47
Were you able to get this working? I have been trying to modify the configuration to enable SWO console output on PB3.

**Comment by wpfundstein** [comment] 2024-03-20 19:21
No. If i Change anything. Add a gpio or other and then create Code i get many Errors by compiling the Code.

**Comment by marekpow** [comment] 2024-03-20 20:31
Try to use [my](https://github.com/marekpow/Wio5E-mini). I it forked from the above repo.

**Comment by wpfundstein** [comment] 2024-03-20 21:24
Try to use [my](https://github.com/marekpow/Wio5E-mini). I it forked from the above repo.

your link is not working.

**Comment by marekpow** [comment] 2024-03-25 19:10
I'm sorry, it was my mistake. The proper URL is [here](https://github.com/marekpow/lorawan-test). 
I forked it from the Seeds Studio repo via a zipped code.

**Comment by thonghatmit** [comment] 2024-05-23 14:16
> I'm sorry, it was my mistake. The proper URL is [here](https://github.com/marekpow/lorawan-test). I forked it from the Seeds Studio repo via a zipped code.

Hi
Sorry, but  i use your repo on the link, the problem is still there when i try assign adc pin for ioc file, when code is generated, it get the same error, file adc_if.c is auto deleted by code generator
![cayvcl](https://github.com/Seeed-Studio/LoRaWan-E5-Node/assets/87261328/6ad540f4-de6c-42ef-85a0-e86f2239befd)

**Comment by mingzhangqun** [comment] 2024-10-16 08:07
Okay, I'll repeat your steps and find out why.

**Comment by Lesords** [comment] 2024-11-04 02:40
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Closed as completed by Lesords** 2024-11-04 02:40 UTC
Labels: UAY, LoRaWan-E5-Node
