### ISSUE TITLE
Timout error in SUBGHZ_SPI_TRANSMIT function 

### ISSUE THREAD

**Issue by hpernet** [Seeed-Studio/LoRaWan-E5-Node#10] opened 2022-07-13 06:10 UTC
Hello, 

I'm trying to developpe a P2P application between two LoRa-E5 mini. 
I reprogram the STM32WL on the board using STM32CubeIDE.

At first, I try to developpe my own application from PINGPONG exemple of STMicroelectronics and your exemples, but while debuging, I found that, in SUBGHZ layer, the SUBGHZ_SPI_TRANSMIT function return Timout error, its looks like the TXE flag of the SubGHz is never set...

I first think that it was from my code, but then, I try to use your LORAWAN end node code exemple, and fall into the same error. The only thing that I modify is that I comment the debug initialization function to be able to debug the code.
I also ty to disable Low Power manager to see if there is a conflict between debug and LPM but nothing change.

Do you have an idea about whats happenning ? 
Do you think this may come by Option byte configuration, or debug configuration ?

You can find here the only things that I try to modify in sys_app.c file : 
![Capture d’écran 2022-07-12 091947](https://user-images.githubusercontent.com/91084729/178662783-0bb511c6-e81b-465c-850d-d58d0d286d86.png)

And my debug config :

![Capture d’écran 2022-07-12 092201](https://user-images.githubusercontent.com/91084729/178662779-43d92dd0-3919-4952-936f-79c3ee59f25b.png)

**Comment by johflo** [comment] 2022-07-29 05:18
Hi,
I made some changes on the STM PingPong example (configuration based on https://github.com/danak6jq/Seeed-LoRa-E5) ) without errors.
https://github.com/johflo/Seeed-Lora-e5
Perhaps you can find the difference of your example.

Johannes

**Comment by hpernet** [comment] 2022-07-29 06:30
Hi @johflo, 

Thanks so much for your answer ! 

I tried your project and I've got the same error... 
It's must come from my side but I don't know whitch configuration...

Do you have any radio problem while using the debug ? 
Is it possible for you to send me your option byte configuration ? 
Did you make some changes on the board to make it work ? 

Thanks 
Hugo

**Comment by johflo** [comment] 2022-07-29 06:48
Hi,

I tested the programm without errors.
since this is my first program I can only debug the init part. After the init the program/debugging changed to run mode so I can't debug the hole program.
In the init part I didn't get some errors.

If you can tell me where I find the option bytes config I can send it.

I build the program on the configuration that I posted before.

Johannes

**Comment by hpernet** [comment] 2022-07-29 06:57
Okey thanks ! 

My error occured in the initialization of the radio.
In stm32wlxx_hal_subghz.c file, when SUBGHZSPI_Transmit function is called.

![image](https://user-images.githubusercontent.com/91084729/181700333-f13a7dd9-13a2-4c98-bd3a-c7f769d1df3b.png)

Maybe that the radio cannot works while debugging...

For option bytes they can be found using STM32Cube debugger in OB menu when you are connected to your device. You should have modified them to program the board with STM32CubeIDE I think.

Hugo

**Comment by johflo** [comment] 2022-07-29 09:21
I will take a look in the evening and I'll report you the settings

**Comment by johflo** [comment] 2022-07-29 18:36
Hi,
I've uploaded the code again. There were some mistakes from the first upload. now should it work.
To the option bytes:
In the STM32CubeProgrammer I changed the RDP to AA
In the STM32CubeIDE I did not changed anything in the debugger menu


Johannes

**Comment by hpernet** [comment] 2022-08-01 06:26
Hi @johflo, 

Thank you very much for your time ! 

But I still have the same problem... 

I even try to program the board using STM32CubeProgrammer and the .hex file, and to put en NUCLEOSTM32WL with pingpong code, but no communications seams to happens. 
I don't know whats happenning... 
It's don't seams to be a firmware problem since I'm using yours.

Did you succed to reproduce my error or is it only on my side ? 
Did you succeed to make some transmissions ? 


Hugo

**Comment by johflo** [comment] 2022-08-01 06:32
Hi,

I can't reproduce your error.
I have two LoRa-e5 mini with wich I can run the program normally. One sends the "Ping", the other sends the "Pong".

I also debugged the programm but I didnt get your error.
Do you tested with my Hex-File?

Johannes

**Comment by johflo** [comment] 2022-08-01 06:44
What type of debugger do you use? STLink V2?

**Comment by hpernet** [comment] 2022-08-01 07:33
I tested with your hex-file, and two LoRa-e5 mini, but I still have the error.
I open a serial interface for debug, and I have only Timout errors : 


`PING PONG
APPLICATION_VERSION: V1.2.0
MW_RADIO_VERSION:    V1.2.0

LORA_MODULATION
LORA_BW=125 kHz
LORA_SF=7
36s278:rand=0
41s005:OnRxTimeout
43s340:Master Tx start
64s499:OnTxTimeout
66s630:Slave Rx start
71s361:OnRxTimeout
73s697:Master Tx start
94s859:OnTxTimeout
96s992:Slave Rx start
101s723:OnRxTimeout`

I use a STlink V2 from a Nucleo board for debug.
Do you use thepower source of the debuger or of the USB connector ?

**Comment by johflo** [comment] 2022-08-01 08:16
on debugg mode i use only the STLink.
On terminal mode (2 arduino serial monitors) I use USB power.

**Comment by johflo** [comment] 2022-08-01 08:17
On the second device do you have the same output?

**Comment by hpernet** [comment] 2022-08-01 08:29
Do you have this type of stlink ? 
https://www.amazon.fr/ElectroWorldFR-Simulateur-Programmeur-Downloader-D%C3%A9bogueur/dp/B09HJQQ1C6/ref=sr_1_1_sspa?keywords=stlink+v2&qid=1659342438&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyOElTUUZENTNQVlMmZW5jcnlwdGVkSWQ9QTA2OTQwNzIxQzcyOFRBSVowOE5aJmVuY3J5cHRlZEFkSWQ9QTAyOTc0NDkxMzhRRUtCMFBTTVMxJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

Yes I have the same output on both devices

**Comment by hpernet** [comment] 2022-08-01 08:29
On debug mode, do you power the device with 3.3V or 5V ?

**Comment by johflo** [comment] 2022-08-01 08:43
I have the same STLink V2. I updated it with the last firmware.
I power the devices with 5V.

do you have on both devices the rand=0?

**Comment by hpernet** [comment] 2022-08-01 08:47
I finally succeed !! 

I had a third board that I never used before, so I tried to flash it and it works ! 

I don't know whats happenning with both others boards...

Yes I have rand = 0 on both devices. I think that is because rand use a subghz feature and the mcu can't communicate with the subghz modem.

Thanks so much for your help @johflo !!

**Comment by johflo** [comment] 2022-08-01 09:59
Hi, 
Good to hear.
I have on both devices randoms different of 0.
One or two times I also have strange behaviours (no debugger found). After a erase in the STM32CubeProgrammer the problem was solved.

**Comment by Advanced-Machine-Intelligence-AMI** [comment] 2024-10-04 11:23
can i get your hex file i am facing issue where rand = 0. Also please tell me whether i should flash same code to both boards without any changes.

**Comment by johflo** [comment] 2024-10-04 11:35
You can download the code and compile it. you can flash the Output on both devices without changes

**Comment by mingzhangqun** [comment] 2024-10-16 08:22
Hello, I'm interested if your problem has been solved.

**Comment by Lesords** [comment] 2024-11-04 02:41
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Closed as completed by Lesords** 2024-11-04 02:41 UTC
Labels: UAY, LoRaWan-E5-Node
